name: "Main"

on:
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - "main"

jobs:

  pack-job:
    name: "Pack"
    uses: "./.github/workflows/pack.yml"
